spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-34-225-159-178.compute-1.amazonaws.com/d8kt7r3g9jgm12
  username: fmzorlhyoonlrl
  password: d9b832dae09c8b78dddf909716da2510efdd8ecdc7feaa559a75220172879f1e
  driver-class-name: org.postgresql.Driver

spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

jwt:
  secret-key: "1221"
  # 30 days
  token.expired-time-ms: 2592000000